const skills = [
  { name: "Javascript", icon: "/images/icons/icon-javascript.png" },
  { name: "Typescript", icon: "/images/icons/icon-Typescript.png" },
  { name: "React", icon: "/images/icons/icon-react.svg" },
  { name: "Next.js", icon: "/images/icons/icon-nextjs.png" },
  { name: "Node.js", icon: "/images/icons/icon-nodejs.svg" },
  { name: "Express.js", icon: "/images/icons/icon-express.svg" },
  { name: "Nest.js", icon: "/images/icons/icon-nest.png" },
  { name: "Socket.io", icon: "/images/icons/icon-socket.svg" },
  { name: "PostgreSQL", icon: "/images/icons/icon-postgresql.png" },
  { name: "MongoDB", icon: "/images/icons/icon-mongodb.svg" },
  { name: "Sass/Scss", icon: "/images/icons/icon-sass.png" },
  { name: "Tailwindcss", icon: "/images/icons/icon-tailwindcss.svg" },
  { name: "Figma", icon: "/images/icons/icon-figma.svg" },
  { name: "Cypress", icon: "/images/icons/icon-cypress.svg" },
  { name: "Storybook", icon: "/images/icons/icon-storybook.png" },
  { name: "Git", icon: "/images/icons/icon-git.png" },
];
export const projects = [
  { name: "Javascript", icon: "/images/icons/icon-javascript.png" },
  { name: "Typescript", icon: "/images/icons/icon-Typescript.png" },
  { name: "React", icon: "/images/icons/icon-react.png" },
  { name: "Next.js", icon: "/images/icons/icon-nextjs.png" },
  { name: "Node.js", icon: "/images/icons/icon-nodejs.png" },
  { name: "Express.js", icon: "/images/icons/icon-express.png" },
  { name: "Nest.js", icon: "/images/icons/icon-nest.png" },
  { name: "Socket.io", icon: "/images/icons/icon-socket.png" },
  { name: "PostgreSQL", icon: "/images/icons/icon-postgresql.png" },
  { name: "MongoDB", icon: "/images/icons/icon-mongodb.png" },
  { name: "Sass/Scss", icon: "/images/icons/icon-sass.png" },
  { name: "Tailwindcss", icon: "/images/icons/icon-tailwindcss.png" },
  { name: "Figma", icon: "/images/icons/icon-figma.png" },
  { name: "Cypress", icon: "/images/icons/icon-cypress.png" },
  { name: "Storybook", icon: "/images/icons/icon-storybook.png" },
  { name: "Git", icon: "/images/icons/icon-git.png" },
];

export default skills;
